USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

USE SCHEMA AIRFLOW_DB.BRONZE;

CREATE OR REPLACE TABLE AIRFLOW_DB.BRONZE.DOCTORS_RAW
(
DOCTOR_ID STRING,
NAME STRING,
GENDER STRING,
SPECIALIZATION STRING,
HOSPITAL_ID STRING,
CITY STRING
);

CREATE OR REPLACE TABLE AIRFLOW_DB.BRONZE.HOSPITALS_RAW
(
HOSPITAL_ID STRING,
HOSPITAL_NAME STRING,
CITY STRING
);

CREATE OR REPLACE TABLE AIRFLOW_DB.BRONZE.PATIENTS_RAW
(
PATIENT_ID STRING,
NAME STRING,
GENDER STRING,
DOB STRING,
CITY STRING
);

CREATE OR REPLACE TABLE AIRFLOW_DB.BRONZE.TREATMENTS_RAW
(
TREATMENT_ID STRING,
VISIT_ID STRING,
TREATMENT_TYPE STRING,
OUTCOME STRING,
COST STRING
);

CREATE OR REPLACE TABLE AIRFLOW_DB.BRONZE.VISITS_RAW
(
VISIT_ID STRING,
PATIENT_ID STRING,
HOSPITAL_ID STRING,
VISIT_DATE STRING,
DEPARTMENT STRING,
DOCTOR_ID STRING
);