USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE AIRFLOW_DB;
USE DATABASE AIRFLOW_DB;

CREATE OR REPLACE SCHEMA BRONZE;
CREATE OR REPLACE SCHEMA SILVER;
CREATE OR REPLACE SCHEMA GOLD;

USE SCHEMA AIRFLOW_DB.BRONZE;
CREATE OR REPLACE STORAGE INTEGRATION AIRFLOW_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::470957633639:role/airflowsnowrole'
STORAGE_ALLOWED_LOCATIONS = ('s3://dea-airflow-data');

    DESC INTEGRATION AIRFLOW_S3_INT;

CREATE OR REPLACE STAGE AIRFLOW_DB.BRONZE.AIRFLOW_S3_STAGE
STORAGE_INTEGRATION = AIRFLOW_S3_INT
URL= 's3://dea-airflow-data';

    ls @AIRFLOW_DB.BRONZE.AIRFLOW_S3_STAGE;

