USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

USE SCHEMA AIRFLOW_DB.SILVER;

CREATE OR REPLACE PROCEDURE AIRFLOW_DB.SILVER.PATIENTS_TRANSFORM_SP()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
CREATE OR REPLACE TABLE AIRFLOW_DB.SILVER.PATIENTS_TRANSFORM AS
SELECT
PATIENT_ID AS PATIENT_ID,
SPLIT_PART(NAME,' ',1) AS PATIENT_FIRST_NAME,
SPLIT_PART(NAME,' ',2) AS PATIENT_LAST_NAME,
GENDER AS PATIENT_GENDER,
CAST(DOB AS DATE) AS PATIENT_DOB,
DATEDIFF(YEAR, DOB, CURRENT_DATE) AS PATIENT_AGE,
CITY AS PATIENT_CITY
FROM AIRFLOW_DB.BRONZE.PATIENTS_RAW;
RETURN 'PATIENTS_TRANSFORM Created Successfully';
END;
$$;

CREATE OR REPLACE PROCEDURE AIRFLOW_DB.SILVER.TREATMENTS_TRANSFORM_SP()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
CREATE OR REPLACE TABLE AIRFLOW_DB.SILVER.TREATMENTS_TRANSFORM AS
SELECT
T.TREATMENT_ID AS PATIENT_TREATMENT_ID,
T.VISIT_ID AS PATIENT_VISIT_ID,
CAST(V.VISIT_DATE AS DATE) AS PATIENT_VISIT_DATE,
T.TREATMENT_TYPE AS TREATMENT_TYPE,
T.OUTCOME AS TREATMENT_OUTCOME,
T.COST AS TREATMENT_COST,
V.PATIENT_ID AS PATIENT_ID,
SPLIT_PART(P.NAME,' ',1) AS PATIENT_FIRST_NAME,
SPLIT_PART(P.NAME,' ',2) AS PATIENT_LAST_NAME,
V.DOCTOR_ID AS DOCTOR_ID,
SPLIT_PART(D.NAME,' ',1) AS DOCTOR_FIRST_NAME,
SPLIT_PART(D.NAME,' ',2) AS DOCTOR_LAST_NAME,
D.SPECIALIZATION AS DOCTOR_SPECIALIZATION,
V.HOSPITAL_ID AS HOSPITAL_ID,
H.HOSPITAL_NAME AS HOSPITAL_NAME,
H.CITY AS HOSPITAL_CITY
FROM AIRFLOW_DB.BRONZE.TREATMENTS_RAW T
JOIN AIRFLOW_DB.BRONZE.VISITS_RAW V ON T.VISIT_ID = V.VISIT_ID
JOIN AIRFLOW_DB.BRONZE.PATIENTS_RAW P ON V.PATIENT_ID = P.PATIENT_ID
JOIN AIRFLOW_DB.BRONZE.DOCTORS_RAW D ON V.DOCTOR_ID = D.DOCTOR_ID
JOIN AIRFLOW_DB.BRONZE.HOSPITALS_RAW H ON V.HOSPITAL_ID = H.HOSPITAL_ID;
RETURN 'TREATMENTS_TRANSFORM Created Successfully';
END;
$$;

CREATE OR REPLACE PROCEDURE AIRFLOW_DB.SILVER.VISITS_TRANSFORM_SP()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
CREATE OR REPLACE TABLE AIRFLOW_DB.SILVER.VISITS_TRANSFORM AS
SELECT
V.VISIT_ID AS PATIENT_VISIT_ID,
CAST(V.VISIT_DATE AS DATE) AS PATIENT_VISIT_DATE,
V.PATIENT_ID AS PATIENT_ID,
SPLIT_PART(P.NAME,' ',1) AS PATIENT_FIRST_NAME,
SPLIT_PART(P.NAME,' ',2) AS PATIENT_LAST_NAME,
V.DOCTOR_ID AS DOCTOR_ID,
SPLIT_PART(D.NAME,' ',1) AS DOCTOR_FIRST_NAME,
SPLIT_PART(D.NAME,' ',2) AS DOCTOR_LAST_NAME,
D.SPECIALIZATION AS DOCTOR_SPECIALIZATION,
V.HOSPITAL_ID AS HOSPITAL_ID,
H.HOSPITAL_NAME AS HOSPITAL_NAME,
V.DEPARTMENT AS HOSPITAL_DEPARTMENT,
H.CITY AS HOSPITAL_CITY
FROM AIRFLOW_DB.BRONZE.VISITS_RAW V
JOIN AIRFLOW_DB.BRONZE.PATIENTS_RAW P ON V.PATIENT_ID = P.PATIENT_ID
JOIN AIRFLOW_DB.BRONZE.DOCTORS_RAW D ON V.DOCTOR_ID = D.DOCTOR_ID
JOIN AIRFLOW_DB.BRONZE.HOSPITALS_RAW H ON V.HOSPITAL_ID = H.HOSPITAL_ID;
RETURN 'VISITS_TRANSFORM Created Successfully';
END;
$$;